/*
 * Copyright 2014 Fruchuxs.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.hsos.ecs.richwps.wpsmonitor.boundary.gui.controls.wps;

import de.hsos.ecs.richwps.wpsmonitor.boundary.gui.WpsMonitorAdminGui;
import de.hsos.ecs.richwps.wpsmonitor.boundary.gui.utils.MessageDialogs;
import de.hsos.ecs.richwps.wpsmonitor.data.entity.WpsEntity;
import de.hsos.ecs.richwps.wpsmonitor.util.Validate;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 * JDialog to edit WPS. Actions with this dialog have an impact on the scheduler
 * and the wps database. All jobs need to unscheduled and replaced with new ones
 * which match the changes of the wps identifier.
 *
 * @author Florian Vogelpohl <floriantobias@gmail.com>
 */
public class WpsEditDialog extends JDialog {

    private final WpsPanel addParentPanel;
    private final WpsMonitorAdminGui monitorMainFrame;

    /**
     * Constructor.
     *
     * @param monitorMainFrame Reference to the MainFrame of this gui
     * @param addParentPanel Parent panel; is needed for delete operation
     */
    public WpsEditDialog(final WpsMonitorAdminGui monitorMainFrame, final WpsPanel addParentPanel) {
        super(monitorMainFrame, true);
        initComponents();

        this.monitorMainFrame = monitorMainFrame;
        this.addParentPanel = Validate.notNull(addParentPanel, "parent");
        this.endpointField.setText(addParentPanel.getWps().getEndpoint().toString());

        appendTitle(addParentPanel.getWps().getEndpoint().toString());
    }

    @Override
    public void setVisible(boolean b) {
        setLocationRelativeTo(monitorMainFrame);

        super.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel uriDecoText = new JLabel();
        endpointField = new JTextField();
        saveButton = new JButton();
        cancelButton = new JButton();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit WPS");
        setIconImage(new ImageIcon(getClass().getResource("/icons/edit.png")).getImage());
        setName("editDialog"); // NOI18N

        uriDecoText.setText("Endpoint");

        endpointField.setName("endpointField"); // NOI18N
        endpointField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                endpointFieldActionPerformed(evt);
            }
        });

        saveButton.setIcon(new ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.setName("saveButton"); // NOI18N
        saveButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setIcon(new ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Info:");

        jLabel2.setText("Changes first affected after a restart (try out  Monitor > Restart)");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cancelButton)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(saveButton))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(uriDecoText)
                            .addGap(43, 43, 43)
                            .addComponent(endpointField, GroupLayout.PREFERRED_SIZE, 300, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(uriDecoText)
                    .addComponent(endpointField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Action behavior for saveButton.
     *
     * @param evt
     */
    private void saveButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

        String wpsEndpoint = endpointField.getText();

        try {
            WpsEntity addWps = new WpsEntity(wpsEndpoint);

            addParentPanel.updateWps(addWps);
            addParentPanel.reInit();

            dispose();
        } catch (MalformedURLException ex) {
            MessageDialogs.showError(this, "Malformed URL", "The entered URL is not valid!");
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void endpointFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_endpointFieldActionPerformed
        saveButtonActionPerformed(evt);
    }//GEN-LAST:event_endpointFieldActionPerformed

    private void appendTitle(String name) {
        this.setTitle(getTitle() + " " + name);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton cancelButton;
    private JTextField endpointField;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
