/*
 * Copyright 2014 FloH.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.hsosnabrueck.ecs.richwps.wpsmonitor.gui;

import de.hsosnabrueck.ecs.richwps.wpsmonitor.utils.Param;
import java.awt.BorderLayout;
import javax.swing.JFrame;

/**
 *
 * @author FloH
 */
public class WpsProcessDialog extends javax.swing.JDialog {
    private JFrame mainFrame;
    
    /**
     * Creates new form ProcessDialog
     */
    public WpsProcessDialog(JFrame mainFrame, boolean modal) {
        super(mainFrame, modal);
        initComponents();
        
        this.mainFrame = Param.notNull(mainFrame, "mainFrame");
    }
    
    private Boolean isNotEmptyProcessName() {
        return !processIdentifierInput.getText().trim().equalsIgnoreCase("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        wpsProcessScrollPane = new javax.swing.JScrollPane();
        addProcessPane = new javax.swing.JPanel();
        createNewProcessButton = new javax.swing.JButton();
        processIdentifierDecoText = new javax.swing.JLabel();
        processIdentifierInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addProcessPane.setLayout(new javax.swing.BoxLayout(addProcessPane, javax.swing.BoxLayout.PAGE_AXIS));
        wpsProcessScrollPane.setViewportView(addProcessPane);

        createNewProcessButton.setText("Create new Process");
        createNewProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createNewProcessButtonActionPerformed(evt);
            }
        });

        processIdentifierDecoText.setText("Process Identifier");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wpsProcessScrollPane)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(processIdentifierDecoText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(processIdentifierInput, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(createNewProcessButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createNewProcessButton)
                    .addComponent(processIdentifierDecoText)
                    .addComponent(processIdentifierInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wpsProcessScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createNewProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createNewProcessButtonActionPerformed
        if(isNotEmptyProcessName()) {
            WpsProcessPanel processPanel = new WpsProcessPanel(mainFrame, processIdentifierInput.getText());
            
            addProcessPane.add(processPanel, BorderLayout.SOUTH);
            addProcessPane.revalidate(); 
        }
    }//GEN-LAST:event_createNewProcessButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addProcessPane;
    private javax.swing.JButton createNewProcessButton;
    private javax.swing.JLabel processIdentifierDecoText;
    private javax.swing.JTextField processIdentifierInput;
    private javax.swing.JScrollPane wpsProcessScrollPane;
    // End of variables declaration//GEN-END:variables
}
