/*
 * Copyright 2014 FloH.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.hsosnabrueck.ecs.richwps.wpsmonitor.gui;

import de.hsosnabrueck.ecs.richwps.wpsmonitor.utils.Param;
import javax.swing.JFrame;

/**
 *
 * @author FloH
 */
public class WpsProcessJobDialog extends javax.swing.JDialog {
    private JFrame mainframe;
    /**
     * Creates new form WpsProcessJobDialog
     */
    public WpsProcessJobDialog(JFrame mainFrame, boolean modal) {
        super(mainFrame, modal);
        initComponents();
        
        this.mainframe = Param.notNull(mainFrame, "mainFrame");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newJobButton = new javax.swing.JButton();
        jobScrollPane = new javax.swing.JScrollPane();
        addJobPane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        newJobButton.setText("New Job");
        newJobButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newJobButtonActionPerformed(evt);
            }
        });

        addJobPane.setLayout(new javax.swing.BoxLayout(addJobPane, javax.swing.BoxLayout.PAGE_AXIS));
        jobScrollPane.setViewportView(addJobPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 307, Short.MAX_VALUE)
                        .addComponent(newJobButton))
                    .addComponent(jobScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jobScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newJobButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newJobButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newJobButtonActionPerformed
        WpsProcessJobEntry newJobEnty = new WpsProcessJobEntry(mainframe);
        addJobPane.add(newJobEnty);
        addJobPane.revalidate();
    }//GEN-LAST:event_newJobButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addJobPane;
    private javax.swing.JScrollPane jobScrollPane;
    private javax.swing.JButton newJobButton;
    // End of variables declaration//GEN-END:variables
}
