/*
 * Copyright 2014 Florian Vogelpohl <floriantobias@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.hsos.ecs.richwps.wpsmonitor.boundary.gui.elements.process;

import de.hsos.ecs.richwps.wpsmonitor.boundary.gui.WpsMonitorAdminGui;
import de.hsos.ecs.richwps.wpsmonitor.control.scheduler.TriggerConfig;
import de.hsos.ecs.richwps.wpsmonitor.data.entity.WpsProcessEntity;
import de.hsos.ecs.richwps.wpsmonitor.util.Validate;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.ScrollPaneConstants;
import javax.swing.WindowConstants;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Shows all configured Quartz triggerss of the selected Wps-Process.
 *
 * @author Florian Vogelpohl <floriantobias@gmail.com>
 */
public class WpsProcessJobDialog extends JDialog {

    private final WpsMonitorAdminGui mainframe;
    private final WpsProcessEntity wpsProcess;

    private static final Logger LOG = LogManager.getLogger();

    /**
     * Creates new form WpsProcessJobDialog.
     *
     * @param mainFrame Reference to the WpsMonitorAdminGui of this gui
     * @param wpsProcess WpsProcessEntity instance to request the right trigger
     */
    public WpsProcessJobDialog(final WpsMonitorAdminGui mainFrame, final WpsProcessEntity wpsProcess) {
        super(mainFrame, true);
        initComponents();

        setLocationRelativeTo(mainFrame);

        this.wpsProcess = wpsProcess;
        this.mainframe = Validate.notNull(mainFrame, "mainFrame");

        init();
    }

    private void init() {
        setTitle(getTitle() + " of " + wpsProcess.getIdentifier());
        List<TriggerConfig> triggers = mainframe.getMonitorReference()
                .getMonitorControl()
                .getTriggers(wpsProcess);

        LOG.debug("init WpsProcessJobDialog");
        for (TriggerConfig config : triggers) {
            WpsProcessJobEntry jobEntryPane = createNewJobEntryPane();
            jobEntryPane.reInit(config);

            LOG.debug("reInit jobEntryPane with {}", config.toString());

            addJobEntryPane(jobEntryPane);
        }
    }
    
    private WpsProcessJobEntry createNewJobEntryPane() {
        return new WpsProcessJobEntry(mainframe, addJobPane, wpsProcess);
    }

    private void addJobEntryPane(final WpsProcessJobEntry pane) {
        addJobPane.add(pane);
        addJobPane.revalidate();
        addJobPane.repaint();
    }

    /**
     * reinitialize the form
     */
    public void reInit() {
        addJobPane.removeAll();
        init();
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newJobButton = new JButton();
        jobScrollPane = new JScrollPane();
        addJobPane = new JPanel();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        JLabel jLabel3 = new JLabel();
        JLabel jLabel4 = new JLabel();
        closeButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add, remove or edit Process Job");
        setIconImage(new ImageIcon(getClass().getResource("/icons/time.png")).getImage());
        setResizable(false);

        newJobButton.setIcon(new ImageIcon(getClass().getResource("/icons/time.png"))); // NOI18N
        newJobButton.setText("New Job");
        newJobButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                newJobButtonActionPerformed(evt);
            }
        });

        jobScrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jobScrollPane.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        addJobPane.setLayout(new BoxLayout(addJobPane, BoxLayout.PAGE_AXIS));
        jobScrollPane.setViewportView(addJobPane);

        jLabel1.setText("Start");

        jLabel2.setText("End");

        jLabel3.setText("Time Unit");

        jLabel4.setText("Interval");

        closeButton.setIcon(new ImageIcon(getClass().getResource("/icons/apply.png"))); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(newJobButton)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(closeButton))
                            .addComponent(jobScrollPane)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 281, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(147, 147, 147)
                        .addComponent(jLabel4)
                        .addGap(39, 39, 39)
                        .addComponent(jLabel3)
                        .addGap(174, 174, 174)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jobScrollPane, GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(newJobButton)
                    .addComponent(closeButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newJobButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_newJobButtonActionPerformed
        WpsProcessJobEntry newJobEntry = createNewJobEntryPane();
        addJobEntryPane(newJobEntry);
    }//GEN-LAST:event_newJobButtonActionPerformed

    private void closeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel addJobPane;
    private JButton closeButton;
    private JScrollPane jobScrollPane;
    private JButton newJobButton;
    // End of variables declaration//GEN-END:variables
}
