/*
 * Copyright 2014 Florian Vogelpohl <floriantobias@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.hsosnabrueck.ecs.richwps.wpsmonitor.presentation.gui.elements;

import de.hsosnabrueck.ecs.richwps.wpsmonitor.data.dataaccess.Range;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.data.entity.MeasuredDataEntity;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.data.entity.WpsProcessEntity;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.presentation.gui.MessageDialogs;
import java.util.Date;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Dialog to show the measured data. The measured data will be shown in a
 * {@link MeasuredDataPane} JPanel in the scoll area of this dialog.
 *
 * @author Florian Vogelpohl <floriantobias@gmail.com>
 */
public class ShowMeasuredData extends javax.swing.JDialog {

    private final WpsMonitorGui monitorMainFrame;
    private final WpsProcessEntity wpsProcess;

    private final static Logger log = LogManager.getLogger();

    /**
     * Constructor.
     * 
     * @param monitorMainFrame Reference to the MainFrame of this gui
     * @param process WpsProcessEntity to select the right measured data
     * @param modal true for modal dialog
     */
    public ShowMeasuredData(WpsMonitorGui monitorMainFrame, WpsProcessEntity process, boolean modal) {
        super(monitorMainFrame, modal);
        initComponents();
        setLocationRelativeTo(monitorMainFrame);

        this.monitorMainFrame = monitorMainFrame;
        this.wpsProcess = process;
    }

    /**
     * Reinitialize the dialog with new data from the database.
     */
    public void recaptureData() {
        Range range = new Range(null, 100);

        log.debug("Recapture Data from process {}", wpsProcess);

        List<MeasuredDataEntity> measuredData = monitorMainFrame.getMonitorReference()
                .getMonitorControl()
                .getMeasuredData(wpsProcess, range);

        // clear
        measuredDataAddPanel.removeAll();

        // add new
        for (MeasuredDataEntity e : measuredData) {
            MeasuredDataPane measuredDataPane = new MeasuredDataPane(e.getCreateTime() + ": " + e.toString());

            measuredDataAddPanel.add(measuredDataPane);
        }

        measuredDataAddPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        measuredDataAddPanel = new javax.swing.JPanel();
        deleteAllButton = new javax.swing.JButton();
        deleteByDateButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        deleteOlderAsDate = new com.toedter.calendar.JDateChooser();
        refreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Measured Data"));

        measuredDataAddPanel.setLayout(new javax.swing.BoxLayout(measuredDataAddPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(measuredDataAddPanel);

        deleteAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        deleteAllButton.setText("Delete All");
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });

        deleteByDateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        deleteByDateButton.setText("Delete");
        deleteByDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteByDateButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Delete all older as");

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(refreshButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteOlderAsDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteByDateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deleteAllButton)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(deleteAllButton)
                        .addComponent(deleteByDateButton))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(refreshButton))
                        .addComponent(deleteOlderAsDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action behavior for the deleteAllButton button.
     * 
     * @param evt 
     */
    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
        this.monitorMainFrame
                .getMonitorReference()
                .getMonitorControl()
                .deleteMeasuredDataOfProcess(wpsProcess);

        recaptureData();
    }//GEN-LAST:event_deleteAllButtonActionPerformed

    /**
     * Action behavior for the deleteByDateButton.
     * 
     * @param evt 
     */
    private void deleteByDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteByDateButtonActionPerformed
        if (deleteOlderAsDate.getDate() == null) {
            MessageDialogs.showError(this, "Error", "Please select a valid Date!");
        } else {
            Date olderAs = deleteOlderAsDate.getDate();

            this.monitorMainFrame
                    .getMonitorReference()
                    .getMonitorControl()
                    .deleteMeasuredDataOfProcess(wpsProcess, olderAs);

            recaptureData();
        }
    }//GEN-LAST:event_deleteByDateButtonActionPerformed

    /**
     * Action behavior for the refreh button.
     * 
     * @param evt 
     */
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        recaptureData();
    }//GEN-LAST:event_refreshButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteByDateButton;
    private com.toedter.calendar.JDateChooser deleteOlderAsDate;
    private javax.swing.JPanel measuredDataAddPanel;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
