/*
 * Copyright 2014 Florian Vogelpohl <floriantobias@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.hsos.ecs.richwps.wpsmonitor.boundary.gui.controls.datasource;

import de.hsos.ecs.richwps.wpsmonitor.boundary.gui.WpsMonitorAdminGui;
import de.hsos.ecs.richwps.wpsmonitor.boundary.gui.datasource.DataSource;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;

/**
 * Representates a DataSource instance GUI element.
 * 
 * @author Florian Vogelpohl <floriantobias@gmail.com>
 */
public class DataSourcePanel extends JPanel {

    private final DataSource source;
    private final WpsMonitorAdminGui monitorMainFrame;
    private final DataSourceDialog parent;

    /**
     * Creates a new DataSourcePanel instance.
     * 
     * @param monitorMainFrame The mainframe of the monitor gui
     * @param parent Parent frame
     * @param source DataSource instance which will be used by this panel
     */
    public DataSourcePanel(final WpsMonitorAdminGui monitorMainFrame, final DataSourceDialog parent, final DataSource source) {
        this.source = source;
        this.monitorMainFrame = monitorMainFrame;
        this.parent = parent;

        initComponents();
        setName(source.getRessource());
        this.dataSourceLabel.setText(source.getUsedDriver());
        this.resourceLabel.setText(source.getRessource());
    }

    /**
     * Gets the DataSource instance of these DataSourcePanel.
     * 
     * @return DataSource instance 
     */
    public DataSource getSource() {
        return source;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        dataSourceLabel = new JLabel();
        deleteSourceButton = new JButton();
        JLabel jLabel1 = new JLabel();
        JLabel jLabel2 = new JLabel();
        resourceLabel = new JLabel();

        setMaximumSize(new Dimension(32767, 116));

        jPanel1.setBorder(BorderFactory.createTitledBorder(""));

        dataSourceLabel.setText("jLabel1");
        dataSourceLabel.setName("dataSourceLabel"); // NOI18N

        deleteSourceButton.setIcon(new ImageIcon(getClass().getResource("/icons/database-delete.png"))); // NOI18N
        deleteSourceButton.setText("Delete");
        deleteSourceButton.setName("deleteSourceButton"); // NOI18N
        deleteSourceButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                deleteSourceButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Driver used:");

        jLabel2.setFont(new Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resource:");

        resourceLabel.setText("jLabel3");
        resourceLabel.setName("resourceLabel"); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resourceLabel)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(deleteSourceButton))
                    .addGroup(GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataSourceLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dataSourceLabel)
                    .addComponent(jLabel1))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(resourceLabel)
                    .addComponent(deleteSourceButton))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteSourceButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_deleteSourceButtonActionPerformed
        parent.removeDataSource(this);
    }//GEN-LAST:event_deleteSourceButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel dataSourceLabel;
    private JButton deleteSourceButton;
    private JLabel resourceLabel;
    // End of variables declaration//GEN-END:variables
}
