/*
 * Copyright 2014 Florian Vogelpohl <floriantobias@gmail.com>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.hsosnabrueck.ecs.richwps.wpsmonitor.boundary.gui.elements.datasource;

import de.hsosnabrueck.ecs.richwps.wpsmonitor.boundary.gui.datasource.DataSourceCreator;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.boundary.gui.datasource.DataSource;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.boundary.gui.datasource.DataSourceException;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.boundary.gui.elements.WpsMonitorAdminGui;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.data.config.MonitorConfig;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.control.event.EventNotFound;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.control.event.MonitorEvent;
import de.hsosnabrueck.ecs.richwps.wpsmonitor.control.event.MonitorEventListener;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.LayoutStyle;
import javax.swing.ScrollPaneConstants;
import javax.swing.WindowConstants;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 *
 * @author Florian Vogelpohl <floriantobias@gmail.com>
 */
public class DataSourceDialog extends javax.swing.JDialog {

    private static final Logger LOG = LogManager.getLogger();

    private final Set<DataSourceCreator> drivers;
    private final Set<DataSource> sources;
    private final WpsMonitorAdminGui mainFrame;

    /**
     * Creates new form DataSourceDialog
     *
     * @param monitorMainFrame
     * @param drivers
     * @param parent
     * @param modal
     */
    public DataSourceDialog(WpsMonitorAdminGui monitorMainFrame, Set<DataSourceCreator> drivers, java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        this.drivers = drivers;
        this.mainFrame = monitorMainFrame;
        this.sources = new HashSet<>();

        initComponents();
        init();
        setLocationRelativeTo(parent);
    }

    private void init() {
        for (DataSourceCreator driver : drivers) {
            driverAddPanel.add(new DataDriverPanel(this, driver));
        }

        readSources();

        try {
            mainFrame.getMonitorReference()
                    .getEventHandler()
                    .registerListener("monitor.shutdown", new MonitorEventListener() {

                        @Override
                        public void execute(MonitorEvent event) {
                            storeSources();
                        }
                    });
        } catch (EventNotFound ex) {
            LOG.warn("Can't register storeSource() Listener at monitor.shutdown Event.", ex);
        }

        driverAddPanel.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel jPanel1 = new JPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        driverAddPanel = new JPanel();
        JPanel jPanel2 = new JPanel();
        JScrollPane jScrollPane2 = new JScrollPane();
        dataSourceAddPanel = new JPanel();
        closeButton = new JButton();
        showWpsOfSourcesButton = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DataCreators- and Resources");
        setResizable(false);

        jPanel1.setBorder(BorderFactory.createTitledBorder("Registered Data Source Creatores"));

        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        driverAddPanel.setLayout(new BoxLayout(driverAddPanel, BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(driverAddPanel);

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(BorderFactory.createTitledBorder("Data Sources"));

        jScrollPane2.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        dataSourceAddPanel.setLayout(new BoxLayout(dataSourceAddPanel, BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(dataSourceAddPanel);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addContainerGap())
        );

        closeButton.setIcon(new ImageIcon(getClass().getResource("/icons/apply.png"))); // NOI18N
        closeButton.setText("Close");
        closeButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        showWpsOfSourcesButton.setText("Show WPS of Sources");
        showWpsOfSourcesButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                showWpsOfSourcesButtonActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(showWpsOfSourcesButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(showWpsOfSourcesButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showWpsOfSourcesButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_showWpsOfSourcesButtonActionPerformed
        showWpsDialog();
    }//GEN-LAST:event_showWpsOfSourcesButtonActionPerformed

    private void closeButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    public void addDataSource(final DataSource source) {
        dataSourceAddPanel.add(new DataSourcePanel(mainFrame, this, source));
        sources.add(source);
        dataSourceAddPanel.revalidate();
    }

    public void removeDataSource(DataSource source) {
        sources.remove(source);
    }

    public void removeDataSource(final DataSource source, final DataSourcePanel panel) {
        dataSourceAddPanel.remove(panel);
        removeDataSource(source);
        revalidate();
        repaint();
    }

    private void storeSources() {
        MonitorConfig config = mainFrame.getMonitorReference()
                .getConfig();

        StringBuilder serializedDataSources = new StringBuilder();
        for (DataSource s : sources) {
            serializedDataSources.append(s.getUsedDriver());
            serializedDataSources.append("||");
            serializedDataSources.append(s.getRessource());
            serializedDataSources.append(";;");
        }

        config.setCustomProperty("datasource", serializedDataSources.toString());
    }

    private void readSources() {
        MonitorConfig config = mainFrame.getMonitorReference()
                .getConfig();

        String dataSources = config.getCustomProperty("datasource");

        if (dataSources != null && !dataSources.isEmpty()) {
            String[] dataSourcesArr = dataSources.split(";;");

            for (String source : dataSourcesArr) {
                String[] sourceResourceDriver = source.split("\\|\\|");
                String driverName = sourceResourceDriver[0];
                String resource = sourceResourceDriver[1];

                for (DataSourceCreator driver : drivers) {
                    if (driver.getCreatorName().equals(driverName)) {
                        try {
                            addDataSource(driver.create(resource));
                        } catch (DataSourceException ex) {
                            LOG.error("Can't restore the DataSource of MonitorConfig custom properties. : ", ex);
                        }
                    }
                }
            }
        }
    }

    public Set<DataSource> getSources() {
        return sources;
    }

    public void showWpsDialog() {
        new WpsDialog(mainFrame, sources, true).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton closeButton;
    private JPanel dataSourceAddPanel;
    private JPanel driverAddPanel;
    private JButton showWpsOfSourcesButton;
    // End of variables declaration//GEN-END:variables
}
