/*
 * Copyright 2014 FloH.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package de.hsosnabrueck.ecs.richwps.wpsmonitor.presentation.gui;

import de.hsosnabrueck.ecs.richwps.wpsmonitor.utils.Param;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 *
 * @author FloH
 */
public class WpsProcessPanel extends javax.swing.JPanel {
    private JFrame mainFrame;
    private JDialog wpsProcessJobDialog;
    /**
     * Creates new form WpsProcessPanel
     */
    public WpsProcessPanel(JFrame mainFrame, final String processName) {
        this.mainFrame = mainFrame;
        initComponents();
        
        this.wpsProcessJobDialog = new WpsProcessJobDialog(mainFrame, true);
        
        this.setMaximumSize(new Dimension(this.getMaximumSize().width, this.getPreferredSize().height));
        processNameText.setText(Param.notNull(processName, "processName"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        processNamedecoText = new javax.swing.JLabel();
        showMeasuredDataButton = new javax.swing.JButton();
        deleteProcessButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        testRequestTextArea = new javax.swing.JTextArea();
        showJobsButton = new javax.swing.JButton();
        saveProcessButton = new javax.swing.JButton();
        testRequestDecoText = new javax.swing.JLabel();
        processNameText = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        processNamedecoText.setText("Process Name:");

        showMeasuredDataButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/performance.png"))); // NOI18N
        showMeasuredDataButton.setText("Show Measuredata");
        showMeasuredDataButton.setEnabled(false);

        deleteProcessButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/trash.png"))); // NOI18N
        deleteProcessButton.setText("Delete");
        deleteProcessButton.setEnabled(false);

        testRequestTextArea.setColumns(20);
        testRequestTextArea.setRows(5);
        jScrollPane1.setViewportView(testRequestTextArea);

        showJobsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clock.png"))); // NOI18N
        showJobsButton.setText("Show Jobs");
        showJobsButton.setEnabled(false);
        showJobsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showJobsButtonActionPerformed(evt);
            }
        });

        saveProcessButton.setBackground(new java.awt.Color(255, 0, 51));
        saveProcessButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save.png"))); // NOI18N
        saveProcessButton.setText("Save");
        saveProcessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProcessButtonActionPerformed(evt);
            }
        });

        testRequestDecoText.setText("Test Request:");

        processNameText.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(processNamedecoText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(processNameText))
                            .addComponent(testRequestDecoText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(showJobsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteProcessButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showMeasuredDataButton))
                            .addComponent(saveProcessButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showMeasuredDataButton)
                            .addComponent(deleteProcessButton)
                            .addComponent(showJobsButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(processNamedecoText)
                            .addComponent(processNameText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveProcessButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(testRequestDecoText, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showJobsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showJobsButtonActionPerformed
        wpsProcessJobDialog.setVisible(true);
    }//GEN-LAST:event_showJobsButtonActionPerformed

    private void saveProcessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProcessButtonActionPerformed
        saveProcessButton.setEnabled(false);
        saveProcessButton.setBackground(new Color(50));
        showJobsButton.setEnabled(true);
        showMeasuredDataButton.setEnabled(true);
        deleteProcessButton.setEnabled(true);
    }//GEN-LAST:event_saveProcessButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteProcessButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel processNameText;
    private javax.swing.JLabel processNamedecoText;
    private javax.swing.JButton saveProcessButton;
    private javax.swing.JButton showJobsButton;
    private javax.swing.JButton showMeasuredDataButton;
    private javax.swing.JLabel testRequestDecoText;
    private javax.swing.JTextArea testRequestTextArea;
    // End of variables declaration//GEN-END:variables
}
